### ISSUE TITLE
Mockup UI with flow for organizer

### ISSUE THREAD

**Issue by kelkel17** [giovannimax/sportzer#11]

**Comment by kelkel17** [comment]
![homepage](https://user-images.githubusercontent.com/23580147/43036255-78cbca4e-8d30-11e8-9996-87ac7d508b8d.png)

**Comment by itsmitchyyyy** [comment]
Mao na ang mockup ui?

**Comment by giovannimax** [comment]
added main layout for organizer modules:
![image](https://user-images.githubusercontent.com/33338418/43062366-297f86e0-8e8b-11e8-8660-a6c2bbf8a7f2.png)

**Comment by itsmitchyyyy** [comment]
nagawa mo na yan doi?

**Comment by giovannimax** [comment]
pull nyo lang
